// Code generated by girgen. DO NOT EDIT.

package vte

import (
	"unsafe"
)

// #include <stdlib.h>
// #include <vte/vte.h>
import "C"

// GetFeatures gets a list of features vte was compiled with.
//
// The function returns the following values:
//
//   - utf8: string with features.
//
func GetFeatures() string {
	var _cret *C.char // in

	_cret = C.vte_get_features()

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}
