// Code generated by girgen. DO NOT EDIT.

package vte

// #include <stdlib.h>
// #include <vte/vte.h>
import "C"

// SPAWN_NO_SYSTEMD_SCOPE: use this as a spawn flag (together with flags from
// Flags) in vte_pty_spawn_async().
//
// Prevents vte_pty_spawn_async() etc. from moving the newly created child
// process to a systemd user scope.
const SPAWN_NO_SYSTEMD_SCOPE = 67108864

// SPAWN_REQUIRE_SYSTEMD_SCOPE: use this as a spawn flag (together with flags
// from Flags) in vte_pty_spawn_async().
//
// Requires vte_pty_spawn_async() etc. to move the newly created child process
// to a systemd user scope; if that fails, the whole spawn fails.
//
// This is supported on Linux only.
const SPAWN_REQUIRE_SYSTEMD_SCOPE = 134217728
