// Code generated by girgen. DO NOT EDIT.

package vte

// #include <stdlib.h>
// #include <vte/vte.h>
import "C"

// MAJOR_VERSION: major version number of the VTE library (e.g. in version 3.1.4
// this is 3).
const MAJOR_VERSION = 0

// MICRO_VERSION: micro version number of the VTE library (e.g. in version 3.1.4
// this is 4).
const MICRO_VERSION = 2

// MINOR_VERSION: minor version number of the VTE library (e.g. in version 3.1.4
// this is 1).
const MINOR_VERSION = 74
